In [1]:
from rdkit.Chem.rdmolfiles import MolFromPDBFile
from rdkit.Chem.rdchem import Mol
from rdkit.Chem import AllChem

import numpy as np
import rdkit.Chem as Chem
from rdkit.Chem import AddHs, AssignStereochemistry, HybridizationType, ChiralType, BondStereo, MolFromMol2File
from rdkit.Chem.AllChem import ComputeGasteigerCharges
import os
import sys
sys.path.append("../../")
from src.data.pocket_utils import get_atom_coordinates, find_pocket_atoms_RDKit
from src.utils.constants import ES_THRESHOLD, METAL_OX_STATES
from tqdm import tqdm 

In [2]:
from src.data.utils import pdb_to_rdkit_mol, mol2_to_rdkit_mol, get_vdw_radius, add_charges_to_molecule, get_node_features, get_edge_features, extract_charges_from_mol2, ionic_interaction_using_distance

In [3]:
def rdkit_mol_featurizer(mol: Mol, 
                         pairwise_function: callable,
                         ) -> tuple: 
    """
    Extracts graph features from a given RDKit molecule object.
    Parameters:
        mol (rdkit.Chem.rdchem.Mol): RDKit molecule object.
        protein_or_ligand_ids (list): A list of ints describing whether each atom in the molecule is a protein (-1) or a ligand (1) atom. 
    Returns:
        node_features (np.ndarray): A 2D array of shape (num_atoms, num_node_features) containing node features:
            (protein_or_ligand_id, atomic_num, atomic_mass, aromatic_indicator, ring_indicator, hybridization, chirality, num_heteroatoms, degree, num_hydrogens, partial_charge, formal_charge, num_radical_electrons)
        edge_features (np.ndarray): A 2D array of shape (num_bonds, num_edge_features) containing edge features.
        edge_indices (np.ndarray): A 2D array of shape (num_bonds, 2) containing the indices of the atoms connected by each bond.
    """

    AssignStereochemistry(mol, force=True, cleanIt=True)

    node_features = get_node_features(mol)
    
    edge_features, edge_indices = get_edge_features(mol, pairwise_function)

    return np.array(node_features, dtype='float64'), np.array(edge_features, dtype='float64'), np.array(edge_indices, dtype='int64')

In [4]:
# Define test cases
test_cases = [("CCCCCCCCCC=C", 0, 10), # expected output: None
              ("C=C", 0, 1), # expected output:  (0, 0, 0, 0, 0, 1.3261131312034182)
              ("CC(=O)O", 2, 3) # expected output: (0, 0, 0, 0, 0, 2.278544145756904)
              ]

def tag_atoms(mol, tag):
    for atom in mol.GetAtoms():
        atom.SetProp('protein_or_ligand', tag)

# Initialize RDKit molecules and conformers
molecules = []
for smiles, a1, a2 in test_cases:
    mol = Chem.MolFromSmiles(smiles)
    AllChem.EmbedMolecule(mol)
    molecules.append((mol, a1, a2))

#tag all of the atoms to be ligands in teh test case
for mol, a1, a2 in molecules:
    tag_atoms(mol, 'ligand')


[09:32:48] Molecule does not have explicit Hs. Consider calling AddHs()
[09:32:48] Molecule does not have explicit Hs. Consider calling AddHs()
[09:32:48] Molecule does not have explicit Hs. Consider calling AddHs()


In [5]:
from src.data.utils import vdw_interactions, ionic_interaction_using_distance, covalent_bonds

#for each molecule in the test case, get the node features and edge features for the different pairwise functions

for mol, a1, a2 in molecules:
    print("pairwise function: vdw_interactions")
    print("Molecule: ", Chem.MolToSmiles(mol))
    print("Node features: ")
    print(rdkit_mol_featurizer(mol, vdw_interactions)[0])
    print("Edge features: ")
    print(rdkit_mol_featurizer(mol, vdw_interactions)[1])
    print("Edge indices: ")
    print(rdkit_mol_featurizer(mol, vdw_interactions)[2])
    print("\n")

    print("pairwise function: ionic_interaction_using_distance")
    print("Molecule: ", Chem.MolToSmiles(mol))
    print("Node features: ")
    print(rdkit_mol_featurizer(mol, ionic_interaction_using_distance)[0])
    print("Edge features: ")
    print(rdkit_mol_featurizer(mol, ionic_interaction_using_distance)[1])
    print("Edge indices: ")
    print(rdkit_mol_featurizer(mol, ionic_interaction_using_distance)[2])
    print("\n")

    print("pairwise function: covalent_bonds")
    print("Molecule: ", Chem.MolToSmiles(mol))
    print("Node features: ")
    print(rdkit_mol_featurizer(mol, covalent_bonds)[0])
    print("Edge features: ")
    print(rdkit_mol_featurizer(mol, covalent_bonds)[1])
    print("Edge indices: ")
    print(rdkit_mol_featurizer(mol, covalent_bonds)[2])
    print("\n")

pairwise function: vdw_interactions
Molecule:  C=CCCCCCCCCC
Node features: 


0it [00:00, ?it/s]
0it [00:00, ?it/s]

11it [00:00, 871.63it/s]
11it [00:00, 1284.88it/s]
11it [00:00, 1587.06it/s]
11it [00:00, 1854.32it/s]
11it [00:00, 2458.69it/s]
11it [00:00, 2704.57it/s]
11it [00:00, 3580.70it/s]
11it [00:00, 4753.49it/s]
11it [00:00, 6913.00it/s]
11it [00:00, 13451.12it/s]
11it [00:00, 262144.00it/s]
11it [00:00, 164.89it/s]


[[ 1.     6.    12.011  0.     0.     3.     0.     0.     1.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     3.     0.     0.     2.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     3.     0.     0.     2.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     3.     0.     0.     2.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     3.     0.     0.     2.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     3.     0.     0.     2.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     3.     0.     0.     2.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     3.     0.     0.     2.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     3.     0.     0.     2.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     2.     0.     0.     2.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     2.     0.     0.     1.     0.
   0.     0.   ]]
Edge features: 


11it [00:00, 1224.65it/s]
11it [00:00, 1420.13it/s]
11it [00:00, 1814.86it/s]
11it [00:00, 1869.73it/s]
11it [00:00, 2428.79it/s]
11it [00:00, 2939.62it/s]
11it [00:00, 3557.51it/s]
11it [00:00, 4380.68it/s]
11it [00:00, 6567.59it/s]
11it [00:00, 13646.06it/s]
11it [00:00, 316009.21it/s]
11it [00:00, 187.47it/s]


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Edge indices: 


11it [00:00, 1336.08it/s]
11it [00:00, 1411.49it/s]
11it [00:00, 1599.55it/s]
11it [00:00, 2036.25it/s]
11it [00:00, 2409.26it/s]
11it [00:00, 2496.61it/s]
11it [00:00, 3453.39it/s]
11it [00:00, 4854.01it/s]
11it [00:00, 4620.20it/s]
11it [00:00, 9589.97it/s]
11it [00:00, 180224.00it/s]
11it [00:00, 106.29it/s]


[[ 0  1]
 [ 1  0]
 [ 0  2]
 [ 2  0]
 [ 0  3]
 [ 3  0]
 [ 1  2]
 [ 2  1]
 [ 1  3]
 [ 3  1]
 [ 2  3]
 [ 3  2]
 [ 2  4]
 [ 4  2]
 [ 2  5]
 [ 5  2]
 [ 3  4]
 [ 4  3]
 [ 3  5]
 [ 5  3]
 [ 4  5]
 [ 5  4]
 [ 4  6]
 [ 6  4]
 [ 5  6]
 [ 6  5]
 [ 5  7]
 [ 7  5]
 [ 5  8]
 [ 8  5]
 [ 6  7]
 [ 7  6]
 [ 6  8]
 [ 8  6]
 [ 7  8]
 [ 8  7]
 [ 7  9]
 [ 9  7]
 [ 8  9]
 [ 9  8]
 [ 8 10]
 [10  8]
 [ 9 10]
 [10  9]]


pairwise function: ionic_interaction_using_distance
Molecule:  C=CCCCCCCCCC
Node features: 


11it [00:00, 172154.27it/s]
11it [00:00, 233016.89it/s]
11it [00:00, 114484.72it/s]
11it [00:00, 240298.67it/s]
11it [00:00, 228402.69it/s]
11it [00:00, 24502.04it/s]
11it [00:00, 186037.68it/s]
11it [00:00, 244112.93it/s]
11it [00:00, 344308.54it/s]
11it [00:00, 228402.69it/s]
11it [00:00, 354902.65it/s]
11it [00:00, 451.32it/s]


[[ 1.     6.    12.011  0.     0.     3.     0.     0.     1.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     3.     0.     0.     2.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     3.     0.     0.     2.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     3.     0.     0.     2.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     3.     0.     0.     2.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     3.     0.     0.     2.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     3.     0.     0.     2.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     3.     0.     0.     2.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     3.     0.     0.     2.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     2.     0.     0.     2.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     2.     0.     0.     1.     0.
   0.     0.   ]]
Edge features: 


11it [00:00, 102755.78it/s]
11it [00:00, 219701.64it/s]
11it [00:00, 223967.69it/s]
11it [00:00, 222885.72it/s]
11it [00:00, 290171.97it/s]
11it [00:00, 256318.58it/s]
11it [00:00, 225060.21it/s]
11it [00:00, 292008.51it/s]
11it [00:00, 297660.28it/s]
11it [00:00, 352193.47it/s]
11it [00:00, 135698.07it/s]
11it [00:00, 839.43it/s]


[[0.         0.         0.         0.         0.         1.48746922]
 [0.         0.         0.         0.         0.         1.48746922]
 [0.         0.         0.         0.         0.         2.50740432]
 [0.         0.         0.         0.         0.         2.50740432]
 [0.         0.         0.         0.         0.         3.04999326]
 [0.         0.         0.         0.         0.         3.04999326]
 [0.         0.         0.         0.         0.         4.42182585]
 [0.         0.         0.         0.         0.         4.42182585]
 [0.         0.         0.         0.         0.         1.485333  ]
 [0.         0.         0.         0.         0.         1.485333  ]
 [0.         0.         0.         0.         0.         2.50769486]
 [0.         0.         0.         0.         0.         2.50769486]
 [0.         0.         0.         0.         0.         3.79374324]
 [0.         0.         0.         0.         0.         3.79374324]
 [0.         0.         0.        

11it [00:00, 154305.50it/s]
11it [00:00, 268240.37it/s]
11it [00:00, 244112.93it/s]
11it [00:00, 313859.48it/s]
11it [00:00, 233016.89it/s]
11it [00:00, 260662.96it/s]
11it [00:00, 269809.03it/s]
11it [00:00, 254902.45it/s]
11it [00:00, 123692.61it/s]
11it [00:00, 316009.21it/s]
11it [00:00, 427197.63it/s]
11it [00:00, 942.93it/s]


[[ 0  1]
 [ 1  0]
 [ 0  2]
 [ 2  0]
 [ 0  3]
 [ 3  0]
 [ 0  4]
 [ 4  0]
 [ 1  2]
 [ 2  1]
 [ 1  3]
 [ 3  1]
 [ 1  4]
 [ 4  1]
 [ 1  5]
 [ 5  1]
 [ 2  3]
 [ 3  2]
 [ 2  4]
 [ 4  2]
 [ 2  5]
 [ 5  2]
 [ 2  6]
 [ 6  2]
 [ 2  8]
 [ 8  2]
 [ 3  4]
 [ 4  3]
 [ 3  5]
 [ 5  3]
 [ 3  6]
 [ 6  3]
 [ 3  7]
 [ 7  3]
 [ 4  5]
 [ 5  4]
 [ 4  6]
 [ 6  4]
 [ 4  7]
 [ 7  4]
 [ 4  8]
 [ 8  4]
 [ 5  6]
 [ 6  5]
 [ 5  7]
 [ 7  5]
 [ 5  8]
 [ 8  5]
 [ 5  9]
 [ 9  5]
 [ 6  7]
 [ 7  6]
 [ 6  8]
 [ 8  6]
 [ 6  9]
 [ 9  6]
 [ 6 10]
 [10  6]
 [ 7  8]
 [ 8  7]
 [ 7  9]
 [ 9  7]
 [ 7 10]
 [10  7]
 [ 8  9]
 [ 9  8]
 [ 8 10]
 [10  8]
 [ 9 10]
 [10  9]]


pairwise function: covalent_bonds
Molecule:  C=CCCCCCCCCC
Node features: 


11it [00:00, 180930.76it/s]
11it [00:00, 297660.28it/s]
11it [00:00, 254902.45it/s]
11it [00:00, 290171.97it/s]
11it [00:00, 281325.27it/s]
11it [00:00, 171514.29it/s]
11it [00:00, 225060.21it/s]
11it [00:00, 156929.74it/s]
11it [00:00, 256318.58it/s]
11it [00:00, 354902.65it/s]
11it [00:00, 369098.75it/s]
11it [00:00, 670.94it/s]


[[ 1.     6.    12.011  0.     0.     3.     0.     0.     1.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     3.     0.     0.     2.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     3.     0.     0.     2.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     3.     0.     0.     2.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     3.     0.     0.     2.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     3.     0.     0.     2.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     3.     0.     0.     2.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     3.     0.     0.     2.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     3.     0.     0.     2.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     2.     0.     0.     2.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     2.     0.     0.     1.     0.
   0.     0.   ]]
Edge features: 


11it [00:00, 334328.58it/s]
11it [00:00, 54407.25it/s]
11it [00:00, 334328.58it/s]
11it [00:00, 215595.07it/s]
11it [00:00, 249391.05it/s]
11it [00:00, 250746.43it/s]
11it [00:00, 249391.05it/s]
11it [00:00, 279620.27it/s]
11it [00:00, 334328.58it/s]
11it [00:00, 36558.91it/s]
11it [00:00, 225060.21it/s]
11it [00:00, 801.93it/s]


[[1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0.]]
Edge indices: 


11it [00:00, 281325.27it/s]
11it [00:00, 229539.02it/s]
11it [00:00, 219701.64it/s]
11it [00:00, 234199.72it/s]
11it [00:00, 290171.97it/s]
11it [00:00, 211639.19it/s]
11it [00:00, 189865.61it/s]
11it [00:00, 123361.88it/s]
11it [00:00, 316009.21it/s]
11it [00:00, 239053.60it/s]
11it [00:00, 118300.88it/s]
11it [00:00, 938.57it/s]


[[ 0  1]
 [ 1  0]
 [ 1  2]
 [ 2  1]
 [ 2  3]
 [ 3  2]
 [ 3  4]
 [ 4  3]
 [ 4  5]
 [ 5  4]
 [ 5  6]
 [ 6  5]
 [ 6  7]
 [ 7  6]
 [ 7  8]
 [ 8  7]
 [ 8  9]
 [ 9  8]
 [ 9 10]
 [10  9]]


pairwise function: vdw_interactions
Molecule:  C=C
Node features: 


2it [00:00, 1736.05it/s]
2it [00:00, 83055.52it/s]
2it [00:00, 609.37it/s]


[[ 1.     6.    12.011  0.     0.     2.     0.     0.     1.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     2.     0.     0.     1.     0.
   0.     0.   ]]
Edge features: 


2it [00:00, 1777.62it/s]
2it [00:00, 43464.29it/s]
2it [00:00, 505.67it/s]


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Edge indices: 


2it [00:00, 1691.93it/s]
2it [00:00, 24600.02it/s]
2it [00:00, 45.48it/s]


[[0 1]
 [1 0]]


pairwise function: ionic_interaction_using_distance
Molecule:  C=C
Node features: 


2it [00:00, 41734.37it/s]
2it [00:00, 62601.55it/s]
2it [00:00, 672.49it/s]


[[ 1.     6.    12.011  0.     0.     2.     0.     0.     1.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     2.     0.     0.     1.     0.
   0.     0.   ]]
Edge features: 


2it [00:00, 79891.50it/s]
2it [00:00, 79891.50it/s]
2it [00:00, 783.40it/s]


[[0.         0.         0.         0.         0.         1.32702271]
 [0.         0.         0.         0.         0.         1.32702271]]
Edge indices: 


2it [00:00, 33825.03it/s]
2it [00:00, 66576.25it/s]
2it [00:00, 585.67it/s]


[[0 1]
 [1 0]]


pairwise function: covalent_bonds
Molecule:  C=C
Node features: 


2it [00:00, 13662.23it/s]
2it [00:00, 77672.30it/s]
2it [00:00, 741.90it/s]


[[ 1.     6.    12.011  0.     0.     2.     0.     0.     1.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     2.     0.     0.     1.     0.
   0.     0.   ]]
Edge features: 


2it [00:00, 24385.49it/s]
2it [00:00, 31184.42it/s]
2it [00:00, 38.70it/s]


[[2. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0.]]
Edge indices: 


2it [00:00, 45590.26it/s]
2it [00:00, 58661.59it/s]
2it [00:00, 585.63it/s]


[[0 1]
 [1 0]]


pairwise function: vdw_interactions
Molecule:  CC(=O)O
Node features: 


4it [00:00, 1079.34it/s]
4it [00:00, 1805.94it/s]
4it [00:00, 2998.61it/s]
4it [00:00, 120699.40it/s]
4it [00:00, 199.55it/s]


[[ 1.     6.    12.011  0.     0.     3.     0.     0.     1.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     2.     0.     2.     3.     0.
   0.     0.   ]
 [ 1.     8.    15.999  0.     0.     2.     0.     1.     1.     0.
   0.     0.   ]
 [ 1.     8.    15.999  0.     0.     2.     0.     1.     1.     0.
   0.     0.   ]]
Edge features: 


4it [00:00, 1754.20it/s]
4it [00:00, 1630.60it/s]
4it [00:00, 4044.65it/s]
4it [00:00, 138654.68it/s]
4it [00:00, 289.77it/s]


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Edge indices: 


4it [00:00, 1474.79it/s]
4it [00:00, 1967.77it/s]
4it [00:00, 1481.43it/s]
4it [00:00, 104857.60it/s]
4it [00:00, 242.58it/s]


[[0 1]
 [1 0]
 [0 2]
 [2 0]
 [0 3]
 [3 0]
 [1 2]
 [2 1]
 [1 3]
 [3 1]
 [2 3]
 [3 2]]


pairwise function: ionic_interaction_using_distance
Molecule:  CC(=O)O
Node features: 


4it [00:00, 104857.60it/s]
4it [00:00, 7925.00it/s]
4it [00:00, 8905.10it/s]
4it [00:00, 153919.41it/s]
4it [00:00, 274.63it/s]


[[ 1.     6.    12.011  0.     0.     3.     0.     0.     1.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     2.     0.     2.     3.     0.
   0.     0.   ]
 [ 1.     8.    15.999  0.     0.     2.     0.     1.     1.     0.
   0.     0.   ]
 [ 1.     8.    15.999  0.     0.     2.     0.     1.     1.     0.
   0.     0.   ]]
Edge features: 


4it [00:00, 117323.19it/s]
4it [00:00, 69042.04it/s]
4it [00:00, 124275.67it/s]
4it [00:00, 125203.10it/s]
4it [00:00, 320.46it/s]


[[0.         0.         0.         0.         0.         1.4733525 ]
 [0.         0.         0.         0.         0.         1.4733525 ]
 [0.         0.         0.         0.         0.         2.38709914]
 [0.         0.         0.         0.         0.         2.38709914]
 [0.         0.         0.         0.         0.         2.46098857]
 [0.         0.         0.         0.         0.         2.46098857]
 [0.         0.         0.         0.         0.         1.24944669]
 [0.         0.         0.         0.         0.         1.24944669]
 [0.         0.         0.         0.         0.         1.3889745 ]
 [0.         0.         0.         0.         0.         1.3889745 ]
 [0.         0.         0.         0.         0.         2.27633709]
 [0.         0.         0.         0.         0.         2.27633709]]
Edge indices: 


4it [00:00, 88768.34it/s]
4it [00:00, 5160.63it/s]
4it [00:00, 9998.34it/s]
4it [00:00, 117323.19it/s]
4it [00:00, 393.17it/s]


[[0 1]
 [1 0]
 [0 2]
 [2 0]
 [0 3]
 [3 0]
 [1 2]
 [2 1]
 [1 3]
 [3 1]
 [2 3]
 [3 2]]


pairwise function: covalent_bonds
Molecule:  CC(=O)O
Node features: 


4it [00:00, 104857.60it/s]
4it [00:00, 73908.44it/s]
4it [00:00, 111107.39it/s]
4it [00:00, 148470.94it/s]
4it [00:00, 337.21it/s]


[[ 1.     6.    12.011  0.     0.     3.     0.     0.     1.     0.
   0.     0.   ]
 [ 1.     6.    12.011  0.     0.     2.     0.     2.     3.     0.
   0.     0.   ]
 [ 1.     8.    15.999  0.     0.     2.     0.     1.     1.     0.
   0.     0.   ]
 [ 1.     8.    15.999  0.     0.     2.     0.     1.     1.     0.
   0.     0.   ]]
Edge features: 


4it [00:00, 125203.10it/s]
4it [00:00, 90687.65it/s]
4it [00:00, 122461.43it/s]
4it [00:00, 4993.22it/s]
4it [00:00, 278.52it/s]


[[1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [2. 0. 1. 0. 0.]
 [2. 0. 1. 0. 0.]
 [1. 0. 1. 0. 0.]
 [1. 0. 1. 0. 0.]]
Edge indices: 


4it [00:00, 102927.71it/s]
4it [00:00, 99864.38it/s]
4it [00:00, 5419.00it/s]
4it [00:00, 111107.39it/s]
4it [00:00, 239.89it/s]

[[0 1]
 [1 0]
 [1 2]
 [2 1]
 [1 3]
 [3 1]]


